// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuzZQDt6eBErRHZK3ZAInanLqHE4iw3oE',
    appId: '1:1027057481100:web:0730b43a791acb845512a9',
    messagingSenderId: '1027057481100',
    projectId: 'portfolio-8d8de',
    authDomain: 'portfolio-8d8de.firebaseapp.com',
    storageBucket: 'portfolio-8d8de.appspot.com',
    measurementId: 'G-6F9E00FKLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtbONJqrRL5n9EQh7Dtd84mL2O_d7wBs8',
    appId: '1:1027057481100:android:755dbe7236b5be105512a9',
    messagingSenderId: '1027057481100',
    projectId: 'portfolio-8d8de',
    storageBucket: 'portfolio-8d8de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDET3kC7HQioMga3nHev52GC5g-i0ckUg4',
    appId: '1:481214437178:ios:579c40ede36882d6412203',
    messagingSenderId: '481214437178',
    projectId: 'zoom-3c767',
    databaseURL: 'https://zoom-3c767-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-3c767.appspot.com',
    iosClientId: '481214437178-inm7fmbvk8lluq8l3m2me2dcqb6o0fkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}