// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPd9VWfQuYWFKpV-Lt51B2OE5JkhMLMfA',
    appId: '1:781442905848:web:8f0a154acd6143efcbad0d',
    messagingSenderId: '781442905848',
    projectId: 'loginapp-83fd6',
    authDomain: 'loginapp-83fd6.firebaseapp.com',
    databaseURL: 'https://loginapp-83fd6-default-rtdb.firebaseio.com',
    storageBucket: 'loginapp-83fd6.appspot.com',
    measurementId: 'G-Y8WM1E7355',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhdZTHR5kAczIg1Ip5u1iigS5Zl7V-tc',
    appId: '1:781442905848:android:3c7cb43d305afa7dcbad0d',
    messagingSenderId: '781442905848',
    projectId: 'loginapp-83fd6',
    databaseURL: 'https://loginapp-83fd6-default-rtdb.firebaseio.com',
    storageBucket: 'loginapp-83fd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSJuMIYWOEyfgNmWJjFncKnxMOswEIe_Y',
    appId: '1:781442905848:ios:162523d65dcbdfc4cbad0d',
    messagingSenderId: '781442905848',
    projectId: 'loginapp-83fd6',
    databaseURL: 'https://loginapp-83fd6-default-rtdb.firebaseio.com',
    storageBucket: 'loginapp-83fd6.appspot.com',
    iosClientId: '781442905848-igfvk99kvr1ggjgsj3jicq78dvhufjc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSJuMIYWOEyfgNmWJjFncKnxMOswEIe_Y',
    appId: '1:781442905848:ios:162523d65dcbdfc4cbad0d',
    messagingSenderId: '781442905848',
    projectId: 'loginapp-83fd6',
    databaseURL: 'https://loginapp-83fd6-default-rtdb.firebaseio.com',
    storageBucket: 'loginapp-83fd6.appspot.com',
    iosClientId: '781442905848-igfvk99kvr1ggjgsj3jicq78dvhufjc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2p49eVPUphHYpW4094f-WCqQESj6abfI',
    appId: '1:781442905848:web:c27c3fa2063e4e4dcbad0d',
    messagingSenderId: '781442905848',
    projectId: 'loginapp-83fd6',
    authDomain: 'loginapp-83fd6.firebaseapp.com',
    databaseURL: 'https://loginapp-83fd6-default-rtdb.firebaseio.com',
    storageBucket: 'loginapp-83fd6.appspot.com',
    measurementId: 'G-S5HFTRLLBC',
  );

}