// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4DdVFRNuwmFfDGoMyHuqDvI2Ei4GrREQ',
    appId: '1:960788493380:web:377e407d5557ca02c17811',
    messagingSenderId: '960788493380',
    projectId: 'taqyem-bd9a0',
    authDomain: 'taqyem-bd9a0.firebaseapp.com',
    storageBucket: 'taqyem-bd9a0.firebasestorage.app',
    measurementId: 'G-S4XKJW0NQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQal3SU0ElA44ky26-mVOcuWWqeT7Ajgs',
    appId: '1:960788493380:android:a1d077e3de765e84c17811',
    messagingSenderId: '960788493380',
    projectId: 'taqyem-bd9a0',
    storageBucket: 'taqyem-bd9a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHwcXjHhI3uh3lxPB04cTsxiTxBGWjPZs',
    appId: '1:960788493380:ios:05eede77ad8bcb06c17811',
    messagingSenderId: '960788493380',
    projectId: 'taqyem-bd9a0',
    storageBucket: 'taqyem-bd9a0.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHwcXjHhI3uh3lxPB04cTsxiTxBGWjPZs',
    appId: '1:960788493380:ios:05eede77ad8bcb06c17811',
    messagingSenderId: '960788493380',
    projectId: 'taqyem-bd9a0',
    storageBucket: 'taqyem-bd9a0.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4DdVFRNuwmFfDGoMyHuqDvI2Ei4GrREQ',
    appId: '1:960788493380:web:99e0c96a6c09eae4c17811',
    messagingSenderId: '960788493380',
    projectId: 'taqyem-bd9a0',
    authDomain: 'taqyem-bd9a0.firebaseapp.com',
    storageBucket: 'taqyem-bd9a0.firebasestorage.app',
    measurementId: 'G-EFJ7MKJD4P',
  );

}